
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-02T15:06:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "32169977bc5ef4928ef89d5ec3782c492c78be2a",
 "version": "4.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
