environment:
  ELECTRON_NO_ATTACH_CONSOLE: 1
  CODE_TESTS_WORKSPACE: "%APPVEYOR_BUILD_FOLDER%\\test\\data"

install:
  - ps: Install-Product node 8.12.0 x64
  - npm install -g npm
  - npm install

platform:
  - x86
  - x64

build: off

test_script:
  - npm test
